name: neobis_smart_tailor
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:

  flutter:
    sdk: flutter


  # UI Style package
  flutter_svg: ^2.0.10+1
  flutter_gen: ^5.3.2
  cupertino_icons: ^1.0.8

  # Navigation Components
  auto_route: ^7.8.4

  # DI (Get It)
  get_it: ^7.6.0
  injectable: ^2.1.2

  # BLoC 
  flutter_bloc: ^8.1.5
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2

  # Local DB
  flutter_secure_storage: ^4.2.1

  # Remote
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1

  # Generated
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2

  # Localization
  slang: ^3.31.0
  slang_flutter: ^3.31.0
  flutter_localizations:
    sdk: flutter
 
  # Utils
  flutter_native_splash: ^2.3.10 
  image_picker: ^1.0.7
  shared_preferences: ^2.2.3
  mask_text_input_formatter: ^2.8.0
  pin_code_fields: ^8.0.1
  fpdart: ^1.1.0
  modal_bottom_sheet: ^2.1.2
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1
  


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  auto_route_generator: ^7.3.2
  flutter_gen_runner:
  injectable_generator: ^2.4.1
  slang_build_runner: ^3.31.0
  

  flutter_lints: ^4.0.0


flutter_native_splash:
  image: assets/images/logo.png
  background_image: assets/images/background.jpg
  ios: true
  web: false
  android_gravity: fill
  fullscreen: true


  android_12:
    color: "#FFCC00"
    image: assets/images/logo.png
    fullscreen: true
    # android_gravity: center
    # ios_content_mode: center
    


flutter:
 uses-material-design: true

 assets:
   - assets/
   - assets/fonts/
   - assets/icons/
   - assets/images/

 fonts:
    # - family: SF-Pro-Display
    #   fonts:
    #     - asset: assets/fonts/SF-Pro-Display-Thin.otf
    #       weight: 100
    #     - asset: assets/fonts/SF-Pro-Display-Light.otf
    #       weight: 300
    #     - asset: assets/fonts/SF-Pro-Display-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/SF-Pro-Display-Medium.otf
    #       weight: 500
    #     - asset: assets/fonts/SF-Pro-Display-Semibold.otf
    #       weight: 600
    #     - asset: assets/fonts/SF-Pro-Display-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/SF-Pro-Display-Black.otf
    #       weight: 900
    - family: SF-Pro-Text
      fonts:
      
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-Black.otf
          weight: 900
       


  